apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment  # The name of the deployment
spec:
  replicas: 1  # The number of replicas to create for the deployment
  selector:
    matchLabels:
      app: client  # The label selector for the deployment
  template:
    metadata:
      labels:
        app: client  # The label for the pod template
    spec:
      containers:
      - name: client-container  # The name of the container
        image: client:latest  # The Docker image to use for the container
        imagePullPolicy: Never  # Whether or not to pull the image from the registry
        ports:
        - containerPort: 3000  # The port to expose on the container

---

apiVersion: v1
kind: Service
metadata:
  name: client-service  # The name of the service
spec:
  selector:
    app: client  # The label selector for the service
  ports:
    - protocol: TCP
      port: 3000  # The port to expose on the service
      targetPort: 3000  # The port to forward traffic to
  type: NodePort  # The type of service to create

---

apiVersion: v1
kind: Service
metadata:
  name: client-service  # The name of the service
spec:
  selector:
    app: client  # The label selector for the service
  ports:
    - protocol: TCP
      port: 3000  # The port to expose on the service
      targetPort: 3000  # The port to forward traffic to
  type: NodePort  # The type of service to create